"use client";

import { useEffect, useRef, useState } from "react";
import { Shell } from "@/components/Shell";
import { PageHeader } from "@/components/PageHeader";
import { api, getToken } from "@/lib/api";
import { FeedbackBar } from "@/components/FeedbackBar";
import { useRouter } from "next/navigation";
import { Download, FileText, Loader2, Plus } from "lucide-react";

export default function ReportsPage() {
  const router = useRouter();
  const viewerRef = useRef<HTMLDivElement>(null);
  const [equipment, setEquipment] = useState<any[]>([]);
  const [reports, setReports] = useState<any[]>([]);
  const [selected, setSelected] = useState<any>(null);
  const [loadingId, setLoadingId] = useState<number | null>(null);
  const [form, setForm] = useState({ report_type: "maintenance", equipment_id: "", title: "" });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  function load() {
    api.reports().then(setReports).catch((e) => setError(e.message));
  }

  function showReport(report: any) {
    setSelected(report);
    setError("");
    requestAnimationFrame(() => {
      viewerRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  }

  async function openReport(id: number) {
    setLoadingId(id);
    setError("");
    try {
      const report = await api.getReport(id);
      showReport(report);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Could not load report");
    } finally {
      setLoadingId(null);
    }
  }

  useEffect(() => {
    if (!getToken()) router.push("/");
    else {
      api.equipment().then(setEquipment).catch(() => {});
      load();
    }
  }, [router]);

  async function generate(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError("");
    try {
      const res = await api.generateReport({
        report_type: form.report_type,
        equipment_id: form.equipment_id ? Number(form.equipment_id) : undefined,
        title: form.title || undefined,
      });
      showReport(res);
      load();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Report generation failed");
    } finally {
      setLoading(false);
    }
  }

  const pred = selected?.content?.rul || selected?.content?.prediction;
  const fp = selected?.content?.risk?.failure_probability ?? pred?.failure_probability;

  return (
    <Shell>
      <PageHeader
        title="Maintenance Reports"
        subtitle="Structured reports with RUL, root cause, citations, spares, and cost impact — generated by LangGraph agents."
      />

      {error && (
        <div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>
      )}

      <div className="grid gap-6 lg:grid-cols-3">
        <form onSubmit={generate} className="panel">
          <h2 className="panel-title mb-4 flex items-center gap-2">
            <Plus className="h-5 w-5" /> Generate Report
          </h2>
          <div className="space-y-3">
            <select className="input" value={form.report_type} onChange={(e) => setForm({ ...form, report_type: e.target.value })}>
              <option value="maintenance">Maintenance Summary</option>
              <option value="abnormal">Abnormal Alert Report</option>
              <option value="executive">Executive Plant Overview</option>
              <option value="diagnosis">AI Diagnosis Report</option>
            </select>
            <select className="input" value={form.equipment_id} onChange={(e) => setForm({ ...form, equipment_id: e.target.value })}>
              <option value="">All plant (executive)</option>
              {equipment.map((eq) => (
                <option key={eq.id} value={eq.id}>{eq.equipment_code} — {eq.name}</option>
              ))}
            </select>
            <input className="input" placeholder="Report title (optional)" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
            <button type="submit" className="btn-primary w-full" disabled={loading}>
              {loading ? "Generating (up to 3 min)…" : "Generate Report"}
            </button>
          </div>
        </form>

        <div className="panel lg:col-span-2">
          <div ref={viewerRef}>
            {selected ? (
              <div>
                <div className="panel-header">
                  <div>
                    <h2 className="text-xl font-bold text-tata-ink">{selected.title}</h2>
                    <p className="text-xs text-tata-muted capitalize">{selected.report_type} · {new Date(selected.created_at).toLocaleString()}</p>
                  </div>
                  <div className="flex gap-2">
                    <button type="button" onClick={() => api.downloadReportPdf(selected.id)} className="btn-secondary text-xs">
                      <Download className="h-4 w-4" /> PDF
                    </button>
                    <FileText className="h-8 w-8 text-tata-muted" />
                  </div>
                </div>

                <div className="mb-4 rounded-xl border border-tata-border bg-white p-4 text-sm whitespace-pre-wrap text-tata-ink/85">
                  {selected.content?.narrative || "No narrative generated."}
                </div>

                {(pred || selected.content?.rul) && (
                  <div className="stat-grid mb-4 grid gap-3 sm:grid-cols-3 text-sm">
                    <div className="stat-card"><p className="stat-label">RUL</p><p className="stat-value">{(pred?.rul_hours ?? selected.content?.rul?.rul_hours)?.toFixed?.(0) ?? "—"}h</p></div>
                    <div className="stat-card"><p className="stat-label">Risk</p><p className="stat-value capitalize">{selected.content?.risk?.risk_level ?? pred?.risk_level ?? "—"}</p></div>
                    <div className="stat-card"><p className="stat-label">Failure prob.</p><p className="stat-value">{fp != null ? `${(Number(fp) * 100).toFixed(0)}%` : "—"}</p></div>
                  </div>
                )}

                {selected.content?.recommended_actions?.immediate?.length > 0 && (
                  <div className="mb-4">
                    <p className="panel-title mb-2">Recommended Actions</p>
                    <ul className="space-y-1 text-sm text-tata-muted">
                      {selected.content.recommended_actions.immediate.map((a: string, i: number) => (
                        <li key={i}>• {a}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {selected.content?.retrieved_documents?.length > 0 && (
                  <div>
                    <p className="panel-title mb-2">Retrieved Documents</p>
                    {selected.content.retrieved_documents.slice(0, 3).map((d: any, i: number) => (
                      <p key={i} className="mb-1 text-xs text-tata-muted">
                        <span className="text-tata-blue">{d.source}</span> · {d.excerpt?.slice(0, 100)}…
                      </p>
                    ))}
                  </div>
                )}

                <div className="mt-4 border-t border-tata-border pt-4">
                  <FeedbackBar
                    onSubmit={async (positive) => {
                      await api.feedback({
                        report_id: selected.id,
                        equipment_id: selected.equipment_id,
                        query: selected.title,
                        recommendation: (selected.content?.narrative || "").slice(0, 4000),
                        source_type: "report",
                        fault_type: selected.content?.diagnosis?.probable_causes?.[0]?.cause,
                        rating: positive ? 5 : 2,
                        correction: positive ? undefined : `Report "${selected.title}" marked as not helpful`,
                        approved: positive,
                      });
                    }}
                  />
                </div>
              </div>
            ) : (
              <p className="text-sm text-tata-muted">Select or generate a report to view structured output.</p>
            )}
          </div>

          <h3 className="panel-title mt-6 mb-2">Report History</h3>
          <div className="space-y-2">
            {reports.length === 0 ? (
              <p className="text-sm text-tata-muted">No saved reports yet — generate one above.</p>
            ) : (
              reports.map((r) => {
                const active = selected?.id === r.id;
                const busy = loadingId === r.id;
                return (
                  <button
                    key={r.id}
                    type="button"
                    onClick={() => openReport(r.id)}
                    disabled={busy}
                    className={`flex w-full items-center justify-between gap-3 rounded-lg border px-4 py-3 text-left text-sm transition-colors ${
                      active
                        ? "border-tata-blue bg-tata-blue-pale/60 ring-1 ring-tata-blue/30"
                        : "border-tata-border bg-white hover:border-tata-blue/40 hover:bg-tata-blue-pale/30"
                    }`}
                  >
                    <div className="min-w-0 flex-1">
                      <p className="truncate font-medium text-tata-ink">{r.title || `Report #${r.id}`}</p>
                      <p className="mt-0.5 text-xs capitalize text-tata-muted">{r.report_type?.replace(/_/g, " ")}</p>
                    </div>
                    <div className="flex shrink-0 items-center gap-2 text-xs text-tata-muted">
                      {busy ? <Loader2 className="h-4 w-4 animate-spin text-tata-blue" /> : null}
                      {new Date(r.created_at).toLocaleDateString()}
                    </div>
                  </button>
                );
              })
            )}
          </div>
        </div>
      </div>
    </Shell>
  );
}
